### ISSUE TITLE
Question regarding the inverse order used when decoding using the Transpose codec.

### ISSUE THREAD

**Issue by zoj613** [scalableminds/zarrita#14]
https://github.com/scalableminds/zarrita/blob/7de598f0b70d458dce0a026df8290c128df1c20c/zarrita/codecs.py#L430-L431

The above snippet seems to compute an `inverse_order` that's identical to the encoder transpose order. Shouldn't the snipped be
```python
for i, x enumerate(self.order):
	inverse_order[x] = i
```
instead?

**Comment by brokkoli71** [comment]
correct, for order permutations that are not self inverse this should produce an error.

**Comment by normanrz** [comment]
Thanks for reporting. This issue is fixed in v0.2.3
