### ISSUE TITLE
reshape should be renamed to resize

### ISSUE THREAD

**Issue by jbms** [scalableminds/zarrita#5]
In numpy, reshape preserves the total number of elements, and rearranges them into the new shape, while resize pads/truncated.

Therefore, resize would be more consistent with numpy.

https://github.com/scalableminds/zarrita/blob/5bf867ab4342adb73ab479d4ce3c346a996d888e/zarrita/array.py#L539

**Comment by normanrz** [comment]
Fixed in https://github.com/scalableminds/zarrita/commit/4110c55f414ecf75e7845db273dd999a3c23f757. Thanks @jbms!
